Repository ucsb-cs156-f24/proj-rec-f24-07, pull requests merged in 2024-11, with the labels that each got.

#48 LD - Create Fixtures for RequestType
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/requestTypeFixtures.js
Labels: Ready-For-Staff

#33 ds - update recommendation request backend
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/main/resources/db/migration/changes/RecommendationRequest.json
Labels: Ready-For-Staff

#50 LD - Create RequestType Form and Table
  frontend/src/main/components/RequestTypes/RequestTypeForm.js
  frontend/src/main/components/RequestTypes/RequestTypeTable.js
  frontend/src/main/utils/requestTypeUtils.js
  frontend/src/stories/components/RequestTypes/RequestTypeForm.stories.js
  frontend/src/stories/components/RequestTypes/RequestTypeTable.stories.js
  frontend/src/tests/components/RequestTypes/RequestTypeForm.test.js
  frontend/src/tests/components/RequestTypes/RequestTypeTable.test.js
  frontend/src/tests/utils/requestTypeUtils.test.js
Labels: 10

#35 nw-remove-diningcommons
  .github/workflows/82-kanban-slack-update.yml
  src/main/java/edu/ucsb/cs156/rec/controllers/UCSBDiningCommonsController.java
  src/main/java/edu/ucsb/cs156/rec/entities/UCSBDiningCommons.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UCSBDiningCommonsRepository.java
  src/main/resources/db/migration/changes/UCSBDiningCommons.json
  src/test/java/edu/ucsb/cs156/rec/controllers/UCSBDiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/web/SwaggerWebIT.java
Labels: 10, Merge Candidate-CI

#34 Remove UCSBDates backend and frontend
  frontend/src/App.js
  frontend/src/fixtures/ucsbDatesFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/UCSBDates/UCSBDateForm.js
  frontend/src/main/components/UCSBDates/UCSBDatesTable.js
  frontend/src/main/pages/UCSBDates/UCSBDatesCreatePage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesEditPage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesIndexPage.js
  frontend/src/main/utils/UCSBDateUtils.js
  frontend/src/stories/components/UCSBDates/UCSBDateForm.stories.js
  frontend/src/stories/components/UCSBDates/UCSBDatesTable.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesCreatePage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesEditPage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/UCSBDates/UCSBDateForm.test.js
  frontend/src/tests/components/UCSBDates/UCSBDatesTable.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesCreatePage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesEditPage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesIndexPage.test.js
  frontend/src/tests/utils/UCSBDateUtils.test.js
  frontend/src/tests/utils/useBackend.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/UCSBDatesController.java
  src/main/java/edu/ucsb/cs156/rec/entities/UCSBDate.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UCSBDateRepository.java
  src/main/resources/db/migration/changes/UCSBDates.json
  src/test/java/edu/ucsb/cs156/rec/controllers/UCSBDatesControllerTests.java
Labels: 10, Merge Candidate-CI

#56 Create fixtures for recommendation requests
  frontend/src/fixtures/recommendationRequestFixtures.js
Labels: 5, Ready-For-Staff

#53 LD - Create Request Type Dropdown Component
  frontend/src/main/components/RequestTypes/RequestTypeDropdown.js
  frontend/src/stories/components/RequestTypes/RequestTypeDropdown.stories.js
  frontend/src/tests/components/RequestTypes/RequestTypeDropdown.test.js
Labels: 10, Ready-For-Staff, Merge Candidate-CI

#44 LD - RequestType Service and Exception
  pom.xml
  src/main/java/edu/ucsb/cs156/rec/ExampleApplicationRunner.java
  src/main/java/edu/ucsb/cs156/rec/errors/EntityAlreadyExistsException.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/main/java/edu/ucsb/cs156/rec/services/RequestTypeService.java
  src/test/java/edu/ucsb/cs156/rec/services/RequestTypeServiceTests.java
Labels: 10, Ready-For-Staff

#46 LD - RequestType Post and Get Operations
  src/main/java/edu/ucsb/cs156/rec/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: 10, Merge Candidate-CI

#71 KA -Update fixtures for recommendation requests based on changes in entity file
  frontend/src/fixtures/recommendationRequestFixtures.js
Labels: 5, Merge Candidate-CI

#73 DS - Updated RR entity, repository, and database migration files
  .github/workflows/58-javadoc-pr.yml
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/main/resources/db/migration/changes/RecommendationRequest.json
Labels: Ready-For-Staff

#54 EW - Remove Restaurants Backend and Frontend
  frontend/src/App.js
  frontend/src/fixtures/restaurantFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Restaurants/RestaurantForm.js
  frontend/src/main/components/Restaurants/RestaurantTable.js
  frontend/src/main/pages/Restaurants/RestaurantCreatePage.js
  frontend/src/main/pages/Restaurants/RestaurantEditPage.js
  frontend/src/main/pages/Restaurants/RestaurantIndexPage.js
  frontend/src/main/utils/restaurantUtils.js
  frontend/src/stories/components/Restaurants/RestaurantForm.stories.js
  frontend/src/stories/components/Restaurants/RestaurantTable.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantCreatePage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantEditPage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Restaurants/RestaurantForm.test.js
  frontend/src/tests/components/Restaurants/RestaurantTable.test.js
  frontend/src/tests/pages/Restaurants/RestaurantCreatePage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantEditPage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantIndexPage.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RestaurantsController.java
  src/main/java/edu/ucsb/cs156/rec/entities/Restaurant.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RestaurantRepository.java
  src/main/resources/db/migration/changes/Restaurants.json
  src/test/java/edu/ucsb/cs156/rec/controllers/ApiControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/controllers/DummyController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RestaurantsControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/integration/RestaurantIT.java
  src/test/java/edu/ucsb/cs156/rec/web/RestaurantWebIT.java
Labels: 10, Ready-For-Staff, Merge Candidate-CI
